ALTER TABLE `BankTransfers` MODIFY COLUMN `amount` bigint NOT NULL;
ALTER TABLE `StaffApplication` MODIFY COLUMN `targetRole` enum('USER','OWNER','CODING-ADMIN','CONTENT-ADMIN','EVENT-ADMIN','MODERATOR-ADMIN','HEAD_MODERATOR','MODERATOR','JR_MODERATOR','HEAD_CONTENT','CONTENT','HEAD_EVENT','EVENT','CODER') NOT NULL;
ALTER TABLE `UserData` MODIFY COLUMN `role` enum('USER','OWNER','CODING-ADMIN','CONTENT-ADMIN','EVENT-ADMIN','MODERATOR-ADMIN','HEAD_MODERATOR','MODERATOR','JR_MODERATOR','HEAD_CONTENT','CONTENT','HEAD_EVENT','EVENT','CODER') NOT NULL DEFAULT 'USER';
ALTER TABLE `War` MODIFY COLUMN `attackerShrineHp` smallint NOT NULL DEFAULT 500;
ALTER TABLE `War` MODIFY COLUMN `attackerShrineMaxHp` smallint NOT NULL DEFAULT 500;
ALTER TABLE `UserData` ADD `dailyWarMissions` smallint unsigned DEFAULT 0 NOT NULL;
ALTER TABLE `VillageElderVote` ADD `activeFlag` int GENERATED ALWAYS AS (CASE WHEN `status` = 'PENDING' THEN 1 ELSE NULL END) STORED;
ALTER TABLE `VillageElderVote` ADD CONSTRAINT `VillageElderVote_active_pending_unique` UNIQUE(`villageId`,`type`,`targetId`,`activeFlag`);
CREATE INDEX `VillageElderVote_initiatedByUserId_idx` ON `VillageElderVote` (`initiatedByUserId`);