ALTER TABLE `ConceptImage` MODIFY COLUMN `done` boolean NOT NULL;
ALTER TABLE `ConceptImage` MODIFY COLUMN `done` boolean NOT NULL DEFAULT false;
ALTER TABLE `Conversation` MODIFY COLUMN `isLocked` boolean NOT NULL;
ALTER TABLE `Conversation` MODIFY COLUMN `isLocked` boolean NOT NULL DEFAULT false;
ALTER TABLE `Conversation` MODIFY COLUMN `isPublic` boolean NOT NULL DEFAULT true;
ALTER TABLE `ConversationComment` MODIFY COLUMN `isPinned` boolean NOT NULL;
ALTER TABLE `ConversationComment` MODIFY COLUMN `isPinned` boolean NOT NULL DEFAULT false;
ALTER TABLE `ForumThread` MODIFY COLUMN `isPinned` boolean NOT NULL;
ALTER TABLE `ForumThread` MODIFY COLUMN `isPinned` boolean NOT NULL DEFAULT false;
ALTER TABLE `ForumThread` MODIFY COLUMN `isLocked` boolean NOT NULL;
ALTER TABLE `ForumThread` MODIFY COLUMN `isLocked` boolean NOT NULL DEFAULT false;
ALTER TABLE `HistoricalAvatar` MODIFY COLUMN `done` boolean NOT NULL;
ALTER TABLE `HistoricalAvatar` MODIFY COLUMN `done` boolean NOT NULL DEFAULT false;
ALTER TABLE `HistoricalSoundEffect` MODIFY COLUMN `done` boolean NOT NULL;
ALTER TABLE `HistoricalSoundEffect` MODIFY COLUMN `done` boolean NOT NULL DEFAULT false;
ALTER TABLE `Item` MODIFY COLUMN `destroyOnUse` boolean NOT NULL;
ALTER TABLE `Item` MODIFY COLUMN `destroyOnUse` boolean NOT NULL DEFAULT false;
ALTER TABLE `PaypalWebhookMessage` MODIFY COLUMN `handled` boolean NOT NULL;
ALTER TABLE `PaypalWebhookMessage` MODIFY COLUMN `handled` boolean NOT NULL DEFAULT false;
ALTER TABLE `UserData` MODIFY COLUMN `approvedTos` boolean NOT NULL;
ALTER TABLE `UserData` MODIFY COLUMN `approvedTos` boolean NOT NULL DEFAULT false;
ALTER TABLE `UserData` MODIFY COLUMN `extraJutsuSlots` tinyint unsigned NOT NULL;
ALTER TABLE `UserJutsu` MODIFY COLUMN `equipped` boolean NOT NULL;
ALTER TABLE `UserJutsu` MODIFY COLUMN `equipped` boolean NOT NULL DEFAULT false;
ALTER TABLE `UserReport` MODIFY COLUMN `adminResolved` boolean NOT NULL;
ALTER TABLE `UserReport` MODIFY COLUMN `adminResolved` boolean NOT NULL DEFAULT false;
CREATE INDEX `ActionLog_createdAt_idx` ON `ActionLog` (`createdAt`);
CREATE INDEX `DataBattleActions_type_idx` ON `DataBattleAction` (`type`);
CREATE INDEX `DataBattleActions_battleWon_idx` ON `DataBattleAction` (`battleWon`);
CREATE INDEX `DataBattleActions_battleType_idx` ON `DataBattleAction` (`battleType`);
CREATE INDEX `DataBattleActions_contentId_idx` ON `DataBattleAction` (`contentId`);