ALTER TABLE `UserReport` MODIFY COLUMN `status` enum('UNVIEWED','REPORT_CLEARED','BAN_ACTIVATED','SILENCE_ACTIVATED','BAN_ESCALATED','SILENCE_ESCALATED','OFFICIAL_WARNING','TRADE_BAN_ACTIVATED') NOT NULL DEFAULT 'UNVIEWED';
ALTER TABLE `UserReport` MODIFY COLUMN `predictedStatus` enum('UNVIEWED','REPORT_CLEARED','BAN_ACTIVATED','SILENCE_ACTIVATED','BAN_ESCALATED','SILENCE_ESCALATED','OFFICIAL_WARNING','TRADE_BAN_ACTIVATED');
ALTER TABLE `UserReportComment` MODIFY COLUMN `decision` enum('UNVIEWED','REPORT_CLEARED','BAN_ACTIVATED','SILENCE_ACTIVATED','BAN_ESCALATED','SILENCE_ESCALATED','OFFICIAL_WARNING','TRADE_BAN_ACTIVATED');
ALTER TABLE `UserData` ADD `isTradeBanned` boolean DEFAULT false NOT NULL;
ALTER TABLE `UserData` ADD `iframesMuted` boolean DEFAULT false NOT NULL;