// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  ninjarpgUserId: __t.string().name("ninjarpg_user_id"),
  sessionSignature: __t.string().name("session_signature"),
  nonce: __t.string(),
  definitionsHash: __t.string().name("definitions_hash"),
  abilityDamage: __t.u32().name("ability_damage"),
  abilityRange: __t.u32().name("ability_range"),
  abilityCooldownMs: __t.u32().name("ability_cooldown_ms"),
  abilityCritChance: __t.f64().name("ability_crit_chance"),
  abilityDamagePerTile: __t.f64().name("ability_damage_per_tile"),
  playerMaxHealth: __t.i32().name("player_max_health"),
  healthRegen: __t.f64().name("health_regen"),
  defensePercent: __t.f64().name("defense_percent"),
  defenseFlat: __t.f64().name("defense_flat"),
  lifestealPercent: __t.f64().name("lifesteal_percent"),
  knockbackChance: __t.f64().name("knockback_chance"),
  knockbackForce: __t.f64().name("knockback_force"),
  tokensPerWave: __t.f64().name("tokens_per_wave"),
  tokensPerKill: __t.f64().name("tokens_per_kill"),
  interestPerWave: __t.f64().name("interest_per_wave"),
  skipEnemyChance: __t.f64().name("skip_enemy_chance"),
  scorePerKill: __t.u32().name("score_per_kill"),
  scoreToPointsRatio: __t.u32().name("score_to_points_ratio"),
  initialGridSize: __t.u32().name("initial_grid_size"),
  maxGridSize: __t.u32().name("max_grid_size"),
  gridExpandFreq: __t.u32().name("grid_expand_freq"),
  rangeVisualFactor: __t.f64().name("range_visual_factor"),
  finalWave: __t.u32().name("final_wave"),
  finalScore: __t.u32().name("final_score"),
  pointsEarned: __t.u32().name("points_earned"),
  completedAt: __t.u64().name("completed_at"),
});
