// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  ninjarpgUserId: __t.string(),
  seed: __t.string(),
  nonce: __t.string(),
  sessionSignature: __t.string(),
  upgradeDefinitionsJson: __t.string(),
  enemyDefinitionsJson: __t.string(),
  abilityDamage: __t.u32(),
  abilityRange: __t.u32(),
  abilityCooldownMs: __t.u32(),
  abilityCritChance: __t.f64(),
  abilityDamagePerTile: __t.f64(),
  playerMaxHealth: __t.i32(),
  healthRegen: __t.f64(),
  defensePercent: __t.f64(),
  defenseFlat: __t.f64(),
  lifestealPercent: __t.f64(),
  knockbackChance: __t.f64(),
  knockbackForce: __t.f64(),
  tokensPerWave: __t.f64(),
  tokensPerKill: __t.f64(),
  interestPerWave: __t.f64(),
  skipEnemyChance: __t.f64(),
  scorePerKill: __t.u32(),
  scoreToPointsRatio: __t.u32(),
  initialGridSize: __t.u32(),
  maxGridSize: __t.u32(),
  gridExpandFreq: __t.u32(),
  rangeVisualFactor: __t.f64(),
};
