// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import HexPosition from "./hex_position_type";


export default __t.row({
  enemyId: __t.u64().primaryKey().name("enemy_id"),
  sessionId: __t.u64().name("session_id"),
  spawnCol: __t.u32().name("spawn_col"),
  spawnRow: __t.u32().name("spawn_row"),
  maxHealth: __t.i32().name("max_health"),
  get path() {
    return __t.array(HexPosition);
  },
});
