// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import HexPosition from "./hex_position_type";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  enemyType: __t.string().name("enemy_type"),
  health: __t.i32(),
  speed: __t.f64(),
  damage: __t.i32(),
  attackCooldown: __t.f64().name("attack_cooldown"),
  spawnCol: __t.u32().name("spawn_col"),
  spawnRow: __t.u32().name("spawn_row"),
  get path() {
    return __t.array(HexPosition);
  },
});
