// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Enemy", {
  id: __t.u64(),
  sessionId: __t.u64(),
  enemyType: __t.string(),
  col: __t.u32(),
  row: __t.u32(),
  health: __t.i32(),
  speed: __t.f64(),
  damage: __t.i32(),
  attackCooldown: __t.f64(),
  lastAttackTime: __t.u64(),
  movementProgress: __t.f64(),
  direction: __t.string(),
  pathIndex: __t.u32(),
});
