// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import HexPosition from "./hex_position_type";

export default __t.object("EnemySpawn", {
  enemyId: __t.u64(),
  sessionId: __t.u64(),
  spawnCol: __t.u32(),
  spawnRow: __t.u32(),
  maxHealth: __t.i32(),
  get path() {
    return __t.array(HexPosition);
  },
});
