// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

import GameLoopSchedule from "./game_loop_schedule_type";

export default {
  get arg() {
    return GameLoopSchedule;
  },
};
