// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  ninjarpgUserId: __t.string().name("ninjarpg_user_id"),
  seed: __t.string(),
  nonce: __t.string(),
  sessionSignature: __t.string().name("session_signature"),
  upgradeDefinitionsJson: __t.string().name("upgrade_definitions_json"),
  enemyDefinitionsJson: __t.string().name("enemy_definitions_json"),
  initialAbilityDamage: __t.u32().name("initial_ability_damage"),
  initialAbilityRange: __t.u32().name("initial_ability_range"),
  initialAbilityCooldownMs: __t.u32().name("initial_ability_cooldown_ms"),
  initialAbilityCritChance: __t.f64().name("initial_ability_crit_chance"),
  initialAbilityDamagePerTile: __t.f64().name("initial_ability_damage_per_tile"),
  initialPlayerMaxHealth: __t.i32().name("initial_player_max_health"),
  initialHealthRegen: __t.f64().name("initial_health_regen"),
  initialDefensePercent: __t.f64().name("initial_defense_percent"),
  initialDefenseFlat: __t.f64().name("initial_defense_flat"),
  initialLifestealPercent: __t.f64().name("initial_lifesteal_percent"),
  initialKnockbackChance: __t.f64().name("initial_knockback_chance"),
  initialKnockbackForce: __t.f64().name("initial_knockback_force"),
  initialTokensPerWave: __t.f64().name("initial_tokens_per_wave"),
  initialTokensPerKill: __t.f64().name("initial_tokens_per_kill"),
  initialInterestPerWave: __t.f64().name("initial_interest_per_wave"),
  initialSkipEnemyChance: __t.f64().name("initial_skip_enemy_chance"),
  scorePerKill: __t.u32().name("score_per_kill"),
  scoreToPointsRatio: __t.u32().name("score_to_points_ratio"),
  initialGridSize: __t.u32().name("initial_grid_size"),
  maxGridSize: __t.u32().name("max_grid_size"),
  gridExpandFreq: __t.u32().name("grid_expand_freq"),
  rangeVisualFactor: __t.f64().name("range_visual_factor"),
  createdAt: __t.u64().name("created_at"),
  spacetimedbIdentity: __t.string().name("spacetimedb_identity"),
});
