// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.object("GameSession", {
  id: __t.u64(),
  ninjarpgUserId: __t.string(),
  seed: __t.string(),
  nonce: __t.string(),
  sessionSignature: __t.string(),
  upgradeDefinitionsJson: __t.string(),
  enemyDefinitionsJson: __t.string(),
  initialAbilityDamage: __t.u32(),
  initialAbilityRange: __t.u32(),
  initialAbilityCooldownMs: __t.u32(),
  initialAbilityCritChance: __t.f64(),
  initialAbilityDamagePerTile: __t.f64(),
  initialPlayerMaxHealth: __t.i32(),
  initialHealthRegen: __t.f64(),
  initialDefensePercent: __t.f64(),
  initialDefenseFlat: __t.f64(),
  initialLifestealPercent: __t.f64(),
  initialKnockbackChance: __t.f64(),
  initialKnockbackForce: __t.f64(),
  initialTokensPerWave: __t.f64(),
  initialTokensPerKill: __t.f64(),
  initialInterestPerWave: __t.f64(),
  initialSkipEnemyChance: __t.f64(),
  scorePerKill: __t.u32(),
  scoreToPointsRatio: __t.u32(),
  initialGridSize: __t.u32(),
  maxGridSize: __t.u32(),
  gridExpandFreq: __t.u32(),
  rangeVisualFactor: __t.f64(),
  createdAt: __t.u64(),
  spacetimedbIdentity: __t.string(),
});
