// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.object("HexPosition", {
  col: __t.u32(),
  row: __t.u32(),
});
