// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.1 (commit bbfa851b45db7096aa2a69d7dbad84f52983559f).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AbandonSessionReducer from "./abandon_session_reducer";
export { AbandonSessionReducer };
import CreateSessionReducer from "./create_session_reducer";
export { CreateSessionReducer };
import DeleteCompletedRunReducer from "./delete_completed_run_reducer";
export { DeleteCompletedRunReducer };
import GameLoopReducer from "./game_loop_reducer";
export { GameLoopReducer };
import PurchaseUpgradeReducer from "./purchase_upgrade_reducer";
export { PurchaseUpgradeReducer };
import StartWaveReducer from "./start_wave_reducer";
export { StartWaveReducer };
import ThrowShurikenReducer from "./throw_shuriken_reducer";
export { ThrowShurikenReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import CompletedRunRow from "./completed_run_table";
export { CompletedRunRow };
import EnemyRow from "./enemy_table";
export { EnemyRow };
import EnemyQueuedRow from "./enemy_queued_table";
export { EnemyQueuedRow };
import EnemySpawnRow from "./enemy_spawn_table";
export { EnemySpawnRow };
import GameLoopScheduleRow from "./game_loop_schedule_table";
export { GameLoopScheduleRow };
import GameSessionRow from "./game_session_table";
export { GameSessionRow };
import ProjectileRow from "./projectile_table";
export { ProjectileRow };
import SessionStateRow from "./session_state_table";
export { SessionStateRow };
import SessionUpgradeRow from "./session_upgrade_table";
export { SessionUpgradeRow };

// Import and reexport all types
import CompletedRun from "./completed_run_type";
export { CompletedRun };
import Enemy from "./enemy_type";
export { Enemy };
import EnemyQueued from "./enemy_queued_type";
export { EnemyQueued };
import EnemySpawn from "./enemy_spawn_type";
export { EnemySpawn };
import GameLoopSchedule from "./game_loop_schedule_type";
export { GameLoopSchedule };
import GameSession from "./game_session_type";
export { GameSession };
import HexPosition from "./hex_position_type";
export { HexPosition };
import Projectile from "./projectile_type";
export { Projectile };
import SessionState from "./session_state_type";
export { SessionState };
import SessionUpgrade from "./session_upgrade_type";
export { SessionUpgrade };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'completed_run',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'completed_run_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CompletedRunRow),
  __table({
    name: 'enemy',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyRow),
  __table({
    name: 'enemy_queued',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'enemy_queued_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EnemyQueuedRow),
  __table({
    name: 'enemy_spawn',
    indexes: [
      { name: 'enemy_id', algorithm: 'btree', columns: [
        'enemyId',
      ] },
    ],
    constraints: [
      { name: 'enemy_spawn_enemy_id_key', constraint: 'unique', columns: ['enemyId'] },
    ],
  }, EnemySpawnRow),
  __table({
    name: 'game_loop_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'game_loop_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, GameLoopScheduleRow),
  __table({
    name: 'game_session',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameSessionRow),
  __table({
    name: 'projectile',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'projectile_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectileRow),
  __table({
    name: 'session_state',
    indexes: [
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'session_state_session_id_key', constraint: 'unique', columns: ['sessionId'] },
    ],
  }, SessionStateRow),
  __table({
    name: 'session_upgrade',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'session_upgrade_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionUpgradeRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("abandon_session", AbandonSessionReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("delete_completed_run", DeleteCompletedRunReducer),
  __reducerSchema("game_loop", GameLoopReducer),
  __reducerSchema("purchase_upgrade", PurchaseUpgradeReducer),
  __reducerSchema("start_wave", StartWaveReducer),
  __reducerSchema("throw_shuriken", ThrowShurikenReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

