// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb/sdk";

export default __t.object("Projectile", {
  id: __t.u64(),
  sessionId: __t.u64(),
  originCol: __t.u32(),
  originRow: __t.u32(),
  targetCol: __t.u32(),
  targetRow: __t.u32(),
  progress: __t.f64(),
  damage: __t.u32(),
  critRoll: __t.f64(),
});


