// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb/sdk";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  originCol: __t.u32().name("origin_col"),
  originRow: __t.u32().name("origin_row"),
  targetCol: __t.u32().name("target_col"),
  targetRow: __t.u32().name("target_row"),
  progress: __t.f64(),
  damage: __t.u32(),
  critRoll: __t.f64().name("crit_roll"),
});
