// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  sessionId: __t.u64().primaryKey().name("session_id"),
  wave: __t.u32(),
  score: __t.u32(),
  gridSize: __t.u32().name("grid_size"),
  playerHealth: __t.i32().name("player_health"),
  playerMaxHealth: __t.i32().name("player_max_health"),
  playerCol: __t.u32().name("player_col"),
  playerRow: __t.u32().name("player_row"),
  inRunCurrency: __t.u32().name("in_run_currency"),
  abilityDamage: __t.u32().name("ability_damage"),
  abilityRange: __t.u32().name("ability_range"),
  abilityCooldownMs: __t.u32().name("ability_cooldown_ms"),
  abilityCritChance: __t.f64().name("ability_crit_chance"),
  abilityDamagePerTile: __t.f64().name("ability_damage_per_tile"),
  abilityLastUsedAt: __t.u64().name("ability_last_used_at"),
  healthRegen: __t.f64().name("health_regen"),
  defensePercent: __t.f64().name("defense_percent"),
  defenseFlat: __t.f64().name("defense_flat"),
  lifestealPercent: __t.f64().name("lifesteal_percent"),
  knockbackChance: __t.f64().name("knockback_chance"),
  knockbackForce: __t.f64().name("knockback_force"),
  tokensPerWave: __t.f64().name("tokens_per_wave"),
  tokensPerKill: __t.f64().name("tokens_per_kill"),
  interestPerWave: __t.f64().name("interest_per_wave"),
  skipEnemyChance: __t.f64().name("skip_enemy_chance"),
  waveInProgress: __t.bool().name("wave_in_progress"),
  waveStartTime: __t.u64().name("wave_start_time"),
  healthRegenAccumulator: __t.f64().name("health_regen_accumulator"),
  nextSpawnAt: __t.u64().name("next_spawn_at"),
  spawnDelayMs: __t.u32().name("spawn_delay_ms"),
  status: __t.string(),
});
