// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default __t.object("SessionState", {
  sessionId: __t.u64(),
  wave: __t.u32(),
  score: __t.u32(),
  gridSize: __t.u32(),
  playerHealth: __t.i32(),
  playerMaxHealth: __t.i32(),
  playerCol: __t.u32(),
  playerRow: __t.u32(),
  inRunCurrency: __t.u32(),
  abilityDamage: __t.u32(),
  abilityRange: __t.u32(),
  abilityCooldownMs: __t.u32(),
  abilityCritChance: __t.f64(),
  abilityDamagePerTile: __t.f64(),
  abilityLastUsedAt: __t.u64(),
  healthRegen: __t.f64(),
  defensePercent: __t.f64(),
  defenseFlat: __t.f64(),
  lifestealPercent: __t.f64(),
  knockbackChance: __t.f64(),
  knockbackForce: __t.f64(),
  tokensPerWave: __t.f64(),
  tokensPerKill: __t.f64(),
  interestPerWave: __t.f64(),
  skipEnemyChance: __t.f64(),
  waveInProgress: __t.bool(),
  waveStartTime: __t.u64(),
  healthRegenAccumulator: __t.f64(),
  nextSpawnAt: __t.u64(),
  spawnDelayMs: __t.u32(),
  status: __t.string(),
});
