// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* tslint:disable */
import { t as __t } from "spacetimedb";

export default {
  sessionId: __t.u64(),
  targetCol: __t.u32(),
  targetRow: __t.u32(),
};
