name: test_linting
on: pull_request
jobs:
  test_linting:
    name: test_linting
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun install
        working-directory: ./app
      - name: run lint
        run: bun run lint
        working-directory: ./app
