name: test_typecheck
on: pull_request
jobs:
  test_typecheck:
    name: test_typecheck
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: install dependencies
        run: bun install
        working-directory: ./app
      - name: run typecheck
        run: bun run typecheck
        working-directory: ./app
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
